language: java
addons:
  sonarcloud:
    organization: "overops"
git:
  depth: false
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=takipi-field_sonar-plugin-overops
